import { Injectable } from '@nestjs/common';
import { FeatureCategoryDto, FeatureDto } from './dto/feature.dto';

@Injectable()
export class FeaturesService {
  private readonly featureCategories: FeatureCategoryDto[] = [
    {
      id: 'core',
      name: 'Core Features',
      description: 'Essential features for every event',
      features: [
        {
          id: 'basic_listing',
          name: 'Basic Event Listing',
          description: 'Create and publish your event listing with basic information',
          basePrice: 0,
          pricingType: 'one_time',
          required: true,
          category: 'core',
        },
        {
          id: 'ticket_sales',
          name: 'Ticket Sales',
          description: 'Sell tickets online with secure payment processing',
          basePrice: 0,
          pricingType: 'per_ticket',
          pricingUnit: 'per ticket sold',
          required: true,
          category: 'core',
        },
      ],
    },
    {
      id: 'design',
      name: 'Design & Branding',
      description: 'Customize your event\'s appearance',
      features: [
        {
          id: 'custom_ticket_design',
          name: 'Custom Ticket Design',
          description: 'Design unique tickets with your branding, colors, and logo',
          basePrice: 5000,
          pricingType: 'one_time',
          category: 'design',
        },
        {
          id: 'premium_templates',
          name: 'Premium Ticket Templates',
          description: 'Access to premium ticket design templates',
          basePrice: 2000,
          pricingType: 'one_time',
          category: 'design',
        },
        {
          id: 'custom_gallery_layout',
          name: 'Custom Gallery Layouts',
          description: 'Choose from 5 different gallery layout styles',
          basePrice: 3000,
          pricingType: 'one_time',
          category: 'design',
          popular: true,
        },
        {
          id: 'event_branding',
          name: 'Event Branding Suite',
          description: 'Custom colors, fonts, and logo placement throughout',
          basePrice: 8000,
          pricingType: 'one_time',
          category: 'design',
        },
      ],
    },
    {
      id: 'tickets',
      name: 'Ticketing Features',
      description: 'Advanced ticketing capabilities',
      features: [
        {
          id: 'qr_codes',
          name: 'QR Code Tickets',
          description: 'Generate QR codes for all tickets (included in ticket sales)',
          basePrice: 0,
          pricingType: 'per_ticket',
          category: 'tickets',
        },
        {
          id: 'dynamic_pricing',
          name: 'Dynamic Pricing',
          description: 'Set pricing tiers based on time, quantity, or demand',
          basePrice: 5000,
          pricingType: 'one_time',
          category: 'tickets',
        },
        {
          id: 'seat_selection',
          name: 'Seat Selection',
          description: 'Interactive seat map with seat selection',
          basePrice: 10000,
          pricingType: 'one_time',
          category: 'tickets',
          popular: true,
        },
        {
          id: 'ticket_transfer',
          name: 'Ticket Transfer',
          description: 'Allow attendees to transfer tickets to others',
          basePrice: 3000,
          pricingType: 'one_time',
          category: 'tickets',
        },
        {
          id: 'waitlist',
          name: 'Waitlist Management',
          description: 'Automatically manage waitlists when events sell out',
          basePrice: 4000,
          pricingType: 'one_time',
          category: 'tickets',
        },
      ],
    },
    {
      id: 'management',
      name: 'Event Management',
      description: 'Tools to manage your event',
      features: [
        {
          id: 'check_in_app',
          name: 'Check-In App',
          description: 'Mobile app for scanning tickets at the event',
          basePrice: 0,
          pricingType: 'per_event',
          pricingUnit: 'per event day',
          category: 'management',
        },
        {
          id: 'advanced_checkin',
          name: 'Advanced Check-In Features',
          description: 'Multiple gates, real-time analytics, duplicate detection',
          basePrice: 5000,
          pricingType: 'per_event',
          category: 'management',
        },
        {
          id: 'staff_management',
          name: 'Staff & Access Control',
          description: 'Manage staff roles, permissions, and access',
          basePrice: 3000,
          pricingType: 'one_time',
          category: 'management',
        },
        {
          id: 'analytics_dashboard',
          name: 'Analytics Dashboard',
          description: 'Comprehensive analytics and reporting',
          basePrice: 0,
          pricingType: 'one_time',
          category: 'management',
        },
        {
          id: 'advanced_analytics',
          name: 'Advanced Analytics',
          description: 'Custom reports, export, and detailed insights',
          basePrice: 5000,
          pricingType: 'one_time',
          category: 'management',
          popular: true,
        },
      ],
    },
    {
      id: 'marketing',
      name: 'Marketing & Promotion',
      description: 'Promote and grow your event',
      features: [
        {
          id: 'email_campaigns',
          name: 'Email Campaigns',
          description: 'Send promotional emails to your audience',
          basePrice: 2000,
          pricingType: 'one_time',
          category: 'marketing',
        },
        {
          id: 'sms_notifications',
          name: 'SMS Notifications',
          description: 'Send SMS updates and reminders',
          basePrice: 2,
          pricingType: 'per_ticket',
          pricingUnit: 'per SMS sent',
          category: 'marketing',
        },
        {
          id: 'social_sharing',
          name: 'Social Media Integration',
          description: 'Easy sharing to Facebook, Twitter, Instagram',
          basePrice: 0,
          pricingType: 'one_time',
          category: 'marketing',
        },
        {
          id: 'affiliate_program',
          name: 'Affiliate Program',
          description: 'Set up an affiliate program with commission tracking',
          basePrice: 5000,
          pricingType: 'one_time',
          category: 'marketing',
        },
        {
          id: 'promo_codes',
          name: 'Promo Codes & Discounts',
          description: 'Create and manage discount codes',
          basePrice: 0,
          pricingType: 'one_time',
          category: 'marketing',
        },
      ],
    },
    {
      id: 'addons',
      name: 'Add-ons & Extras',
      description: 'Additional features and services',
      features: [
        {
          id: 'merchandise',
          name: 'Merchandise Sales',
          description: 'Sell event merchandise alongside tickets',
          basePrice: 4000,
          pricingType: 'one_time',
          category: 'addons',
        },
        {
          id: 'sponsor_management',
          name: 'Sponsor Management',
          description: 'Showcase sponsors with tiered visibility',
          basePrice: 3000,
          pricingType: 'one_time',
          category: 'addons',
        },
        {
          id: 'live_streaming',
          name: 'Live Streaming Integration',
          description: 'Integrate with streaming platforms',
          basePrice: 8000,
          pricingType: 'one_time',
          category: 'addons',
        },
        {
          id: 'multi_language',
          name: 'Multi-Language Support',
          description: 'Support multiple languages for your event',
          basePrice: 6000,
          pricingType: 'one_time',
          category: 'addons',
        },
        {
          id: 'priority_support',
          name: 'Priority Support',
          description: '24/7 priority customer support',
          basePrice: 10000,
          pricingType: 'per_month',
          pricingUnit: 'per month',
          category: 'addons',
        },
      ],
    },
  ];

  findAll(): FeatureCategoryDto[] {
    return this.featureCategories;
  }
}

